INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Marszałkowska 5', 'mpastuszka@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR,2,CURRENT_TIMESTAMP), 5, 'Pastuszka', 12, '+48 555 543 123');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Marszałkowska 5', 's.khanimirzaee@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR,2,CURRENT_TIMESTAMP), 5, 'Samaneh', 12, '+48 555 321 123');

INSERT INTO RESERVATIONS(ADDRESS, EMAIL,  START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, SURNAME, TABLE_NUMBER, PHONE_NUMBER)
VALUES ('Marszałkowska 5', 'sami_khani@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR,2,CURRENT_TIMESTAMP), 5, 'Sami', 12, '+48 555 543 456');